package controllers;

public enum Command {
    B_MENU,B_SHOPPING_CARD,SING_OFF,BUY_CARD,ADD_CASH,
    JP_HOME,JP_TECH,JP_GAMES,JP_FOOD,JP_CLOTHES,BUY_TOTAL_PRODUCTS,
    US_LANGUAGE,ES_LANGUAGE,CONTINUE_BUY,
    B_LOGIN,B_EXIT,B_REGISTER;
}
