package controllers;

public enum Command {
    LOAD_IMAGE,SAVE_PRODUCT,MODIFY_PRODUCT,JD_DELETE_PRODUCT,DIALOG_DELETE,CANCEL_SEARCH,JD_SEARCH_PRODUCT,
    T_PRODUCT,T_CLIENTS,EXIT,ADD_PRODUCT,DELETE_PRODUCT,SEARCH_PRODUCT,CANCEL_DELETE,
    B_MENU,US_LANGUAGE,ES_LANGUAGE;
}
